version: "3"

services:
  adhan_time:
    build: .
    ports:
      - 8084:8084
    entrypoint: []
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8084", "--reload"]
    volumes:
      - ./:/code/
